### PR TITLE
Change the db call so the path is call from the .env, and made a condtion for jumping lines in content

### PR DESCRIPTION
**Pull request by KeerhemFR**

### CODE REVIEW

**Review by Um-Brehon — DISMISSED** [review]
no evil here :)

**Review by Hacene010 — DISMISSED** [review]

**Review by Um-Brehon — DISMISSED** [review]
no evil :)

**Review by Hacene010 — DISMISSED** [review]

**Comment by KeerhemFR** [comment]
Need another review because of a merge due to a conflict ... again

**Review by Hacene010 — APPROVED** [review]

**Review by Um-Brehon — APPROVED** [review]
uhhh, no evil? xD

**Pull request merged**
